// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: stock.proto

package stock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TickerClient is the client API for Ticker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerClient interface {
	// GET the average price of a stock over a period of time
	GetAvgPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error)
}

type tickerClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerClient(cc grpc.ClientConnInterface) TickerClient {
	return &tickerClient{cc}
}

func (c *tickerClient) GetAvgPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error) {
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, "/Ticker/getAvgPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerServer is the server API for Ticker service.
// All implementations must embed UnimplementedTickerServer
// for forward compatibility
type TickerServer interface {
	// GET the average price of a stock over a period of time
	GetAvgPrice(context.Context, *StockRequest) (*StockResponse, error)
	mustEmbedUnimplementedTickerServer()
}

// UnimplementedTickerServer must be embedded to have forward compatible implementations.
type UnimplementedTickerServer struct {
}

func (UnimplementedTickerServer) GetAvgPrice(context.Context, *StockRequest) (*StockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvgPrice not implemented")
}
func (UnimplementedTickerServer) mustEmbedUnimplementedTickerServer() {}

// UnsafeTickerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerServer will
// result in compilation errors.
type UnsafeTickerServer interface {
	mustEmbedUnimplementedTickerServer()
}

func RegisterTickerServer(s grpc.ServiceRegistrar, srv TickerServer) {
	s.RegisterService(&Ticker_ServiceDesc, srv)
}

func _Ticker_GetAvgPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerServer).GetAvgPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ticker/getAvgPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerServer).GetAvgPrice(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ticker_ServiceDesc is the grpc.ServiceDesc for Ticker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ticker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ticker",
	HandlerType: (*TickerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAvgPrice",
			Handler:    _Ticker_GetAvgPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock.proto",
}
